spring.application.name=speech
spring.datasource.url=jdbc:mysql://localhost:3306/transcription_db
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
openai.api.key=${OPENAI_API_KEY}